Repository Vuologist/bumpie, pull requests merged in 2020-12, with the labels that each got.

#162 Forgot password page
  client-react/src/Routes.js
  client-react/src/assets/PaperAirPlaneAndFolder.svg
  client-react/src/authentication/index.js
Labels: enhancement

#165 Feat: add user-settings page
  client-react/src/App.js
  client-react/src/Routes.js
  client-react/src/common/Footer.js
  client-react/src/user-settings/index.js
Labels: enhancement

#169 create category summary box ui
  client-react/src/dashboard/CategorySummary.js
  client-react/src/dashboard/PentagonBox.js
Labels: enhancement

#175 Subcategory one bugfix
  client-react/src/dashboard/CategoryBox.js
Labels: bug

#174 Feat: reveal public facing pages
  client-react/src/Routes.js
  client-react/src/about-us/index.js
  client-react/src/common/navbar.js
  client-react/src/faq/index.js
  client-react/src/home/index.js
Labels: enhancement

#166 Feat: create change email layout
  client-react/src/Routes.js
  client-react/src/common/SettingsSectionHeader.js
  client-react/src/common/TextInput.js
  client-react/src/index.css
  client-react/src/libs/validator.js
  client-react/src/user-settings/ChangeEmail.js
Labels: enhancement

#177 added in hexagon ui and config it to look like design
  client-react/package-lock.json
  client-react/package.json
  client-react/src/dashboard/PentagonBox.js
Labels: enhancement

#167 Feat: add change password layout
  client-react/src/Routes.js
  client-react/src/libs/validator.js
  client-react/src/user-settings/ChangePassword.js
Labels: enhancement

#173 Feat: add change name layout
  client-react/src/Routes.js
  client-react/src/user-settings/ChangeName.js
Labels: enhancement

#178 Del btn func
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/SubCategory.js
  client-react/src/dashboard/index.js
Labels: enhancement

#181 Calc Summary Logic + Radar Chart Functionality
  client-react/src/dashboard/CategorySummary.js
  client-react/src/dashboard/PentagonBox.js
  client-react/src/dashboard/index.js
Labels: enhancement

#180 Connect Category Names with Category Summary/Legend
  client-react/src/App.js
  client-react/src/common/Footer.js
  client-react/src/common/Header.js
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/CategorySummary.js
  client-react/src/dashboard/PentagonBox.js
  client-react/src/dashboard/index.js
  client-react/src/notification-settings/index.js
  client-react/src/user-settings/ChangeEmail.js
  client-react/src/user-settings/ChangeName.js
  client-react/src/user-settings/ChangePassword.js
  client-react/src/user-settings/index.js
Labels: enhancement

#182 add editable subcat names
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/Dropdown.js
  client-react/src/dashboard/SubCategory.js
Labels: enhancement

#190 fix a subcat editing bug & dropdown issue
  client-react/src/common/HeaderDropdown.js
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/Dropdown.js
  client-react/src/dashboard/SubCategory.js
  client-react/src/dashboard/index.js
Labels: bug, enhancement
