Repository Vuologist/bumpie, pull requests merged in 2021-01, with the labels that each got.

#192 bugfix for subcat bug
  client-react/src/dashboard/index.js
Labels: bug

#195 Landing Page Fix up
  client-react/src/assets/CoffeeSwirls.svg
  client-react/src/assets/PostItsSwirls.svg
  client-react/src/assets/clipboard_swirls.svg
  client-react/src/common/Footer.js
  client-react/src/home/index.js
Labels: bug, enhancement

#194 fix for limit of 5 per subcat
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/index.js
Labels: bug

#198 fixed bug
  client-react/src/dashboard/CategoryBox.js
  client-react/src/dashboard/SubCategory.js
  client-react/src/dashboard/index.js
Labels: bug

#206 Feat: add uuid for new users
  bumpie-app-api/infrastructure/.gitignore
  bumpie-app-api/infrastructure/CustomForgotPassword.js
  bumpie-app-api/infrastructure/lib/CognitoAuthRole.js
  bumpie-app-api/infrastructure/lib/CognitoStack.js
  bumpie-app-api/infrastructure/package.json
  client-react/package-lock.json
  client-react/package.json
  client-react/src/authentication/index.js
  client-react/src/config.js
Labels: enhancement

#202 Swirls landing
  client-react/src/assets/allswirlslarge.svg
  client-react/src/assets/allswirlstogether.svg
  client-react/src/home/index.js
Labels: enhancement
